docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - Reference:
        - Translation: translation.md
        - 'View Helpers': view-helpers.md
        - Filters: filters.md
        - Validators: validators.md
site_name: zend-i18n
site_description: Zend\I18n
repo_url: 'https://github.com/zendframework/zend-i18n'
copyright: 'Copyright (c) 2016 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
